### ISSUE TITLE
joystick.AppleRemote.xml typo causes problem with Apple Remote

### ISSUE THREAD

**Issue by chriscurtis** [plexinc/plex-mediastream#4]
Post by CW: http://forums.plexapp.com/index.php/topic/34431-simplex/page__view__findpost__p__224233

Quoting:
for any of you that have found since updating to Laika that you've lost control of your music playback using an Apple Remote, here's the fix. Simply open the joystick.AppleRemote.xml file which is located in /Applications/Plex.app/Contents/Resources/Plex/system/keymaps. Scroll down the very bottom and you'll see the following:

```
  <NowPlaying>
    <joystick name="Apple Remote">
      <button id="1">VolumeUp</button>                                  <!--- Up --->
      <button id="2">VolumeDown</button>                                <!--- Down --->
      <button id="3">SkipPrevious</button>                              <!--- Left --->
      <button id="4">SkipNext</button>                                  <!--- Right --->
      <button id="5">Pause</button>                                     <!--- Play --->
      <button id="6">PreviousMenu</button>                              <!--- Menu --->
      <button id="9">Rewind</button>                                    <!--- Hold Left --->
      <button id="10">FastForward</button>                              <!--- Hold Right --->
      <button id="8">Stop</button>                                     <!--- Hold Menu --->
    </joystick>
  </NowPlaying>
</keymap> 
```

Simply rename &lt;joystick name="Apple Remote"> to &lt;joystick name="AppleRemote"> in other words remove the space between Apple and Remote and then save the file. You should find that you can now control music playback using Plex Laika.

**Comment by elan** [comment]
Fixed in HEAD, thanks!
